master:
  build:
    context: .
    dockerfile: Dockerfile-alpine
  environment:
    JAVA_OPTS: "-Djava.awt.headless=true"
  ports:
    - "50000:50000"
    - "8888:8080"
  volumes:
    - /var/jenkins_home
